#!/bin/bash

# usage
# ./weaveMock <WEAVE_COMMAND> [...args...]
#
WEAVE_COMMAND=$1
echo $* > ./weaveMockArgs

case "$WEAVE_COMMAND" in
  launch-router)
    echo 237c9ccf14e89a6e23fb15f2d9132efd98878f6267b9f128f603be3b3e362472
    ;;
  attach)
    echo 10.0.17.38
    ;;
  died-attach)
    echo "container died" >&2
    exit 1
    ;;
  retry-attach)
    if [[ -f ./attempt ]]; then
      rm ./attempt
      echo 10.0.17.38
      exit 0
    fi

    echo "1" > ./attempt
    echo "temp fail" >&2
    exit 1
    ;;
esac